# Generated by Django 5.2 on 2025-04-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conv_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('from_field', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='itassist.conversation')),
            ],
        ),
    ]
