# Generated by Django 5.2.1 on 2025-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itassist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("receiver_email", models.EmailField(max_length=254)),
                ("file_name", models.CharField(max_length=255)),
                ("blob_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
